<a href="https://colab.research.google.com/github/Jig3008/DataScienceProject1/blob/main/MainProgram.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This is a sample project which gives deeper understanding of how Reliance shares are trading over the last year. The data is downloaded from https://www.nseindia.com/get-quotes/equity?symbol=RELIANCE. The objective of doing this to perform Pandas operations, Data Wrangling and getting further insights of everyday trade.

# **## Step 1: Load the data**

In [2]:
#Welcome to the sample project of Python Pandas and Data Wrangling

In [47]:
#import the pandas library
import pandas as pd
#get the shares data of reliance in the sharesData DataFrame
sharesData = pd.read_csv('relianceSharesData.csv')
sharesData.head(10)

,Date,series,OPEN,HIGH,LOW,PREV. CLOSE,ltp,close,vwap,52W H,52W L,VOLUME,VALUE,No of trades
0,24-Jul-2024,EQ,"2,970.00","3,019.00","2,952.80","2,975.80","2,988.00","2,991.40","2,987.68","3,217.60","2,220.30","59,56,681","17,79,66,51,407.60","2,32,120"
1,23-Jul-2024,EQ,"3,002.00","3,011.50","2,926.00","3,001.35","2,970.05","2,975.80","2,969.60","3,217.60","2,220.30","90,26,022","26,80,36,49,945.60","3,84,359"
2,22-Jul-2024,EQ,"3,074.50","3,075.00","2,998.55","3,110.30","3,004.00","3,001.35","3,016.24","3,217.60","2,220.30","98,37,188","29,67,13,39,998.45","4,65,224"
3,19-Jul-2024,EQ,"3,172.00","3,179.95","3,105.60","3,173.35","3,116.95","3,110.30","3,128.40","3,217.60","2,220.30","65,70,195","20,55,41,78,349.45","2,13,186"
4,18-Jul-2024,EQ,"3,152.00","3,187.80","3,115.65","3,152.50","3,170.60","3,173.35","3,155.52","3,217.60","2,220.30","61,49,187","19,40,39,09,511.40","2,12,178"
5,16-Jul-2024,EQ,"3,187.00","3,200.00","3,138.25","3,194.45","3,148.30","3,152.50","3,166.04","3,217.60","2,220.30","46,93,419","14,85,95,48,266.10","2,30,262"
6,15-Jul-2024,EQ,"3,208.90","3,211.70","3,171.00","3,193.45","3,193.60","3,194.45","3,191.40","3,217.60","2,220.30","26,64,844","8,50,45,91,755.00","1,87,867"
7,12-Jul-2024,EQ,"3,169.00","3,210.30","3,149.00","3,161.30","3,195.00","3,193.45","3,186.07","3,217.60","2,220.30","64,62,392","20,58,96,34,191.20","2,46,838"
8,11-Jul-2024,EQ,"3,175.00","3,208.50","3,141.00","3,168.45","3,170.00","3,161.30","3,169.61","3,217.60","2,220.30","59,70,473","18,92,40,71,474.55","2,46,252"
9,10-Jul-2024,EQ,"3,190.00","3,195.00","3,126.30","3,180.55","3,164.00","3,168.45","3,154.77","3,217.60","2,220.30","35,67,289","11,25,39,68,347.05","1,82,113"

# **## Step 2: After the intial data is loaded. We would work on cleaning the data:[Data Wrangling]**
1. Assign the right data types to columns
2. Drop the columns which are not needed
3. Remove the leading or trailing spaces present

In [48]:
#Step2 : Identify which columns have the data that are needed and the data types of each column
#Also check if the column name themselves have any leading or trailing spaces

sharesData.columns

Index(['Date ', 'series ', 'OPEN ', 'HIGH ', 'LOW ', 'PREV. CLOSE ', 'ltp ',
       'close ', 'vwap ', '52W H ', '52W L ', 'VOLUME ', 'VALUE ',
       'No of trades '],
      dtype='object')

In [49]:
#As we see from the above there are spaces present - we need to correct them
sharesData.columns = sharesData.columns.str.strip()

sharesData.columns

Index(['Date', 'series', 'OPEN', 'HIGH', 'LOW', 'PREV. CLOSE', 'ltp', 'close',
       'vwap', '52W H', '52W L', 'VOLUME', 'VALUE', 'No of trades'],
      dtype='object')

In [50]:
#Check the data types of each column present

sharesData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 249 entries, 0 to 248
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          249 non-null    object
 1   series        249 non-null    object
 2   OPEN          249 non-null    object
 3   HIGH          249 non-null    object
 4   LOW           249 non-null    object
 5   PREV. CLOSE   249 non-null    object
 6   ltp           249 non-null    object
 7   close         249 non-null    object
 8   vwap          249 non-null    object
 9   52W H         249 non-null    object
 10  52W L         249 non-null    object
 11  VOLUME        249 non-null    object
 12  VALUE         249 non-null    object
 13  No of trades  249 non-null    object
dtypes: object(14)
memory usage: 27.4+ KB

In [51]:
#after checking the vaue its apparent that the columns are not tagged to the right data types - lets correct them
#We would also need to correct them we need to remove the , from the decimal values

floatColumns = ['OPEN','HIGH','LOW','PREV. CLOSE','ltp','close','vwap','52W H','52W L','VALUE']

for col in floatColumns:
  sharesData[col] = sharesData[col].str.replace(pat=',',repl='',regex=False).astype('float64')

sharesData.info()

intColumns = ['VOLUME','No of trades']

for col in intColumns:
  sharesData[col] = sharesData[col].str.replace(pat=',',repl='',regex=False).astype('int64')

sharesData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 249 entries, 0 to 248
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          249 non-null    object
 1   series        249 non-null    object
 2   OPEN          249 non-null    float64
 3   HIGH          249 non-null    float64
 4   LOW           249 non-null    float64
 5   PREV. CLOSE   249 non-null    float64
 6   ltp           249 non-null    float64
 7   close         249 non-null    float64
 8   vwap          249 non-null    float64
 9   52W H         249 non-null    float64
 10  52W L         249 non-null    float64
 11  VOLUME        249 non-null    object
 12  VALUE         249 non-null    float64
 13  No of trades  249 non-null    object
dtypes: float64(10), object(4)
memory usage: 27.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 249 entries, 0 to 248
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          249 non-null    object
 1   series        249 non-null    object
 2   OPEN          249 non-null    float64
 3   HIGH          249 non-null    float64
 4   LOW           249 non-null    float64
 5   PREV. CLOSE   249 non-null    float64
 6   ltp           249 non-null    float64
 7   close         249 non-null    float64
 8   vwap          249 non-null    float64
 9   52W H         249 non-null    float64
 10  52W L         249 non-null    float64
 11  VOLUME        249 non-null    int64
 12  VALUE         249 non-null    float64
 13  No of trades  249 non-null    int64
dtypes: float64(10), int64(2), object(2)
memory usage: 27.4+ KB

In [52]:
#Lets check the series column - as it seems categorical data - what data is truly present

sharesData['series'].value_counts()

series
EQ    249
Name: count, dtype: int64

In [53]:
#We know this data is for equity so we would remove the column, we also do not need the LTP, Close, Vwap columns
columns_to_drop = ['ltp','series','close','vwap']
sharesData = sharesData.drop(
    labels=columns_to_drop,
    axis =1
)

sharesData.head()

,Date,OPEN,HIGH,LOW,PREV. CLOSE,52W H,52W L,VOLUME,VALUE,No of trades
0,24-Jul-2024,2970.0,3019.00,2952.80,2975.80,3217.6,2220.3,5956681,1.779665e+10,232120
1,23-Jul-2024,3002.0,3011.50,2926.00,3001.35,3217.6,2220.3,9026022,2.680365e+10,384359
2,22-Jul-2024,3074.5,3075.00,2998.55,3110.30,3217.6,2220.3,9837188,2.967134e+10,465224
3,19-Jul-2024,3172.0,3179.95,3105.60,3173.35,3217.6,2220.3,6570195,2.055418e+10,213186
4,18-Jul-2024,3152.0,3187.80,3115.65,3152.50,3217.6,2220.3,6149187,1.940391e+10,212178

In [55]:
#While we are at it let us work on the column names too - as they are not in symmetry

sharesData.columns = sharesData.columns.str.title()
sharesData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 249 entries, 0 to 248
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          249 non-null    object
 1   Open          249 non-null    float64
 2   High          249 non-null    float64
 3   Low           249 non-null    float64
 4   Prev. Close   249 non-null    float64
 5   52W H         249 non-null    float64
 6   52W L         249 non-null    float64
 7   Volume        249 non-null    int64
 8   Value         249 non-null    float64
 9   No Of Trades  249 non-null    int64
dtypes: float64(7), int64(2), object(1)
memory usage: 19.6+ KB

# **## Step 3: Data Analysis**
1. What day was the highest number of trades done?
2. Check the difference between the highest and lowest trading value for each day?
3. Check which day had the highest difference between the opening and closing?
4. Check for a specific day - what was the opening and closing values?
5. Find the percentage changes between the opening and closing values?

In [82]:
highestTrade = sharesData.sort_values(by='No Of Trades',ascending=False)
highestTrade.head(10)

,Date,Open,High,Low,Prev. Close,52W H,52W L,Volume,Value,No Of Trades,Difference Opening/Closing,Difference Percentage
34,04-Jun-2024,2996.10,2996.10,2718.60,3020.65,3029.00,2220.3,18354549,5.214186e+10,687198,277.50,10.207460
131,11-Jan-2024,2659.00,2725.00,2657.00,2650.10,2725.00,2220.3,11862926,3.197929e+10,581952,68.00,2.559277
35,03-Jun-2024,2966.00,3029.00,2918.00,2860.80,3029.00,2220.3,10763971,3.205590e+10,527552,111.00,3.803975
17,28-Jun-2024,3062.05,3162.00,3062.05,3061.10,3162.00,2220.3,14478668,4.518085e+10,484009,99.95,3.264153
33,05-Jun-2024,2844.00,2862.30,2768.20,2794.55,3029.00,2220.3,8732445,2.463700e+10,474290,94.10,3.399321
2,22-Jul-2024,3074.50,3075.00,2998.55,3110.30,3217.60,2220.3,9837188,2.967134e+10,465224,76.45,2.549566
120,29-Jan-2024,2729.00,2905.00,2720.35,2706.15,2905.00,2220.3,11946719,3.395565e+10,464414,184.65,6.787730
248,24-Jul-2023,2481.00,2514.95,2469.30,2538.75,2630.95,2469.3,11863933,2.956012e+10,441158,45.65,1.848702
18,27-Jun-2024,3027.50,3075.00,3012.00,3028.05,3075.00,2220.3,14191515,4.338326e+10,437882,63.00,2.091633
130,12-Jan-2024,2719.80,2746.65,2691.50,2719.80,2746.65,2220.3,7506082,2.048775e+10,434055,55.15,2.049043

In [64]:
sharesData['Difference Opening/Closing'] = sharesData['High'] - sharesData['Low']
sharesData['Difference Percentage'] = (sharesData['Difference Opening/Closing']/sharesData['Low'])*100
sharesData.head()

,Date,Open,High,Low,Prev. Close,52W H,52W L,Volume,Value,No Of Trades,Difference Opening/Closing,Difference Percentage
0,24-Jul-2024,2970.0,3019.00,2952.80,2975.80,3217.6,2220.3,5956681,1.779665e+10,232120,66.20,2.241940
1,23-Jul-2024,3002.0,3011.50,2926.00,3001.35,3217.6,2220.3,9026022,2.680365e+10,384359,85.50,2.922078
2,22-Jul-2024,3074.5,3075.00,2998.55,3110.30,3217.6,2220.3,9837188,2.967134e+10,465224,76.45,2.549566
3,19-Jul-2024,3172.0,3179.95,3105.60,3173.35,3217.6,2220.3,6570195,2.055418e+10,213186,74.35,2.394062
4,18-Jul-2024,3152.0,3187.80,3115.65,3152.50,3217.6,2220.3,6149187,1.940391e+10,212178,72.15,2.315729

In [68]:
#lets analyze the statistical values for the column
sharesData['Difference Percentage'].describe()

count    249.000000
mean       1.695704
std        0.983285
min        0.409042
25%        1.045877
50%        1.551248
75%        2.065374
max       10.207460
Name: Difference Percentage, dtype: float64

In [70]:
#looking at the above it seems that there are instances where the max deviation is more than 10

shares_Deviation_gt10 = sharesData[sharesData['Difference Percentage'] > 10]
shares_Deviation_gt10.head()

,Date,Open,High,Low,Prev. Close,52W H,52W L,Volume,Value,No Of Trades,Difference Opening/Closing,Difference Percentage
34,04-Jun-2024,2996.1,2996.1,2718.6,3020.65,3029.0,2220.3,18354549,5.214186e+10,687198,277.5,10.20746

In [ ]:
#above output shows only 1 day where it deviating 10%

In [81]:
#lets check what was the highest value, lowest value, number of trades and difference value for July 19, 2024

July19Data = sharesData.loc[3,['High','Low','No Of Trades']].to_frame().T
July19Data

      High     Low No Of Trades
3  3179.95  3105.6       213186